---
- name: Ansible-NAS
  hosts: all
  gather_facts: yes
  become: yes
  become_user: root
  vars_files:
    - vars/nas.yml

  roles:
    - role: os
    - role: firewall
    - role: account
    - role: mount
    - role: samba
    - role: minidlna
