---
# Fedora 39
- name: T540
  hosts: t540
  gather_facts: yes
  become: true
  vars_files:
    - vars/t540.yml

  roles:
    - role: os
    - role: sshd
    - role: firewall
    - role: account
    - role: bertvv.hosts
      vars:
         hosts_add_ansible_managed_hosts: true
         hosts_network_interface: 'wlp4s0'