---
- name: Set login banner
  ansible.builtin.copy:
    src: motd.txt
    dest: /etc/motd
  when:
    - ansible_login_banner is defined

- name: "Install extra packages"
  ansible.builtin.package:
    name: "{{ item }}"
    state: present
  with_items: "{{ ansible_nas_extra_packages }}"
  when:
    - ansible_nas_extra_packages is defined
    - ansible_nas_extra_packages | length > 0

- name: "Set Hostname"
  ansible.builtin.import_tasks: hostname.yml
  when:
    - ansible_nas_hostname is defined

- name: "Set Timezone"
  community.general.timezone:
    name: "{{ ansible_nas_timezone }}"
  when:
    - ansible_nas_timezone is defined

- name: "Set Locales"
  community.general.locale_gen:
    name: "{{ item }}"
    state: present
  with_items: "{{ server_locales }}"
  when:
    - server_locales is defined
    - server_locales | length > 0

- name: "Set Selinux"
  ansible.posix.selinux:
    policy: targeted
    state: "{{ selinux_state }}"
  when:
    - selinux_state is defined
    - selinux_state != ""

- name: "Configure Kernel parameters"
  ansible.posix.sysctl:
    name: "{{ sysctl.name }}"
    value: "{{ sysctl.value }}"
    state: present
  with_items: "{{ sysctl_entries }}"
  loop_control:
    loop_var: sysctl
  when:
    - sysctl_entries is defined
    - sysctl_entries | length > 0

- name: "Set if turning off screen should keep running"
  ansible.builtin.lineinfile:
    path: "/etc/systemd/logind.conf"
    state: present
    regexp: "^HandleLidSwitch="
    line: "HandleLidSwitch={{ screen_turn_off_mode }}"

- name: "Set default editor"
  ansible.builtin.lineinfile:
    path: "{{ global_bash_rc }}"
    state: present
    line: "export EDITOR=vim"

- name: "Set default systemctl target "
  ansible.builtin.file:
    src: "/usr/lib/systemd/system/{{ systemctl_default_target }}"
    dest: /etc/systemd/system/default.target
    state: link
