---
- ansible.builtin.assert:
    that:
      - firewall_service_package is defined
    quiet: true

- name: "Install Firewall Service Package: {{ firewall_service_package }}"
  ansible.builtin.package:
    name: "{{ firewall_service_package }}"
    state: present

- name: "Configure Firewall Service for {{ firewall_service_package }}"
  ansible.builtin.include_tasks: "{{ firewall_service_package }}.yml"
