---
- name: Make sure UFW Service is started and enabled
  ansible.builtin.service:
    name: "ufw"
    state: "started"
    enabled: yes

- name: "Allow common services in ufw"
  community.general.ufw:
    rule: "{{ item.rule | default('allow') }}"
    port: "{{ item.port }}"
    proto: "{{ item.proto | default('tcp') }}"
    state: "{{ item.state | default('enabled') }}"
  with_items: "{{ (firewall_common_allowed_services | default([])) | union(customized_allowed_services | default([])) }}"
