---
- name: Install minidlna
  ansible.builtin.package:
    name: "{{ minidlna_package}}"
    state: present

- name: Configure minidlna
  ansible.builtin.template:
    src: "minidlna.conf.j2"
    dest: /etc/minidlna.conf
  notify:
    - start minidlna
