---
- name: "Make sure ssh server package is installed"
  ansible.builtin.package:
    name: openssh-server
    state: present

- name: "Checks SSHd configuration"
  ansible.builtin.template:
    src: templates/sshd_config.j2
    dest: /etc/ssh/sshd_config
    group: root
    owner: root
  notify:
    - restart sshd

- name: "Ensure SSHd is running"
  ansible.builtin.service:
    name: sshd
    state: started
    enabled: yes
